version: "3.3"

services:

   wordpress:
      build: .
      restart: always
      ports: 
         - 8080:80
      environment: 
         WORDPRESS_DB_HOST: db
         WORDPRESS_DB_USER: WORDPRESS_DB_USER
         WORDPRESS_DB_PASSWORD: wppassword
         WORDPRESS_DB_NAME: wpdb
      volumes: volumes
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
      

   db:
      image: mysql:5.7
      restart: always
      environment:
         MYSQL_DATABASE: wpdb
         MYSQL_USER: wpuser
         MYSQL_PASSWORD: wppass
         MYSQL_RANDOM_ROOT_PASSWORD: "1"
      VOLUMES:
         -db:/var/lib/mysql

   adminer:
         depends_on:
            - db
         image: adminer
         restart: always
         ports:
            - 8888:8080

networks: 
   back:

volumes:
   db: